% Called by FinalProject_NM_031217.m to create a line plot showing the 
% change in mean Poisson Error with increasing planes. The plot has error bars
% that represent 2 standard deviations of the Poisson Error.
%
% USAGE:
%       figh = PoissonError( minorisotope, isotope )
%
% INPUTS:
%       minorisotope        An array of the minor isotope's counts/s from the
%                           the depth profile .dat data table. The table is 
%                           generated by Look@NanoSIMS and is found in the 'dat' folder
%       isotope             1 = oxygen, 2 = carbon, 3 = nitrogen
% 
% OUTPUTS:
%       figh                Figure handle of resulting figure.
%       
% Created by Nicolette Meyer on 02 December 2017

function figh = PoissonError( minorisotope, isotope )
%Getting the dimensions of the minorisotope array
[nrow ncol] = size(minorisotope);

%Removing the columns of errors from the minorisotope array
minorisotope2 = minorisotope(:, (2:2:ncol));

%Making a new array of cumulative counts/s for each ROI over the planes
cumulative = zeros(nrow,(ncol-1)/2);
cumulative(1,:) = minorisotope2(1,:);
for plane = 2:nrow
    for ROI = 1:((ncol-1)/2)
        cumulative(plane,ROI) = cumulative((plane-1),ROI)+minorisotope2(plane,ROI);
    end
end

%Calculating the poisson error for the cumulative counts/s    
PEtable = ((1./cumulative).^0.5).*1000;

%Getting the mean poisson error for all the ROIs for each plane
summaryPE = zeros(nrow,3);
summaryPE(:,1) = minorisotope(:,1);
for plane = 1:nrow
    summaryPE(plane,2) = mean(PEtable(plane,:));
    summaryPE(plane,3) = 2.*std(PEtable(plane,:));
end

%Making a line plot of the change in poisson error over the # of planes
elementlabel = ["Oxygen", "Carbon", "Nitrogen"];
figh = figure(gcf);
    hold on;
    errorbar(summaryPE(:,1), summaryPE(:,2), summaryPE(:,3)), 'black';
    %The plot has error bars that represent 2SD of the Poisson Error
    plot(summaryPE(:,1), summaryPE(:,2));
    xlabel('Plane');
    ylabel(sprintf('%s Mean Poisson Error (permil, +-2SD)', elementlabel(isotope)));
    yl = ylim; %obtaining the y-axis' limits
    yl = [0, yl(2)]; %setting the y-axis' lower limit to 0
    ylim(yl);
    hold off;
end

